package com.example.ui.ingredients

import com.example.ui.R

fun getDrawableResIdForItem(index: Int): Int {
    return when (index) {
        0 -> R.drawable.light_rum
        1 -> R.drawable.applejack
        2 -> R.drawable.gin
        3 -> R.drawable.dark_rum
        4 -> R.drawable.sweet_vermout
        5 -> R.drawable.strawberry_schnapps
        6 -> R.drawable.scotch
        7 -> R.drawable.apricot_brandy
        8 -> R.drawable.triple_sec
        9 -> R.drawable.southern_comfort
        10 -> R.drawable.orange_bitters
        11 -> R.drawable.brandy
        12 -> R.drawable.lemon_vodka
        13 -> R.drawable.blended_whiskey
        14 -> R.drawable.dry_vermouth
        15 -> R.drawable.amaretto
        16 -> R.drawable.tea
        17 -> R.drawable.champagne
        18 -> R.drawable.coffe_liqueur
        19 -> R.drawable.bourbon
        20 -> R.drawable.tequila
        21 -> R.drawable.vodka
        22 -> R.drawable.anejo_rum
        23 -> R.drawable.bitters
        24 -> R.drawable.sugar
        25 -> R.drawable.kahlua
        26 -> R.drawable.demerara_sugar
        27 -> R.drawable.dubonnet_rouge
        28 -> R.drawable.watermelon
        29 -> R.drawable.lime_juice
        30 -> R.drawable.irish_whiskey
        31 -> R.drawable.apple_brandy
        32 -> R.drawable.carbonated_water
        33 -> R.drawable.cherry_brandy
        34 -> R.drawable.creme_de_cacao
        35 -> R.drawable.grenadine
        36 -> R.drawable.port
        37 -> R.drawable.coffee_brandy
        38 -> R.drawable.red_wine
        39 -> R.drawable.rum
        40 -> R.drawable.grapefruit_juice
        41 -> R.drawable.ricard
        42 -> R.drawable.sherry
        43 -> R.drawable.cognac
        44 -> R.drawable.sloe_gin
        45 -> R.drawable.apple_juice
        46 -> R.drawable.pineapple_juice
        47 -> R.drawable.lemon_juice
        48 -> R.drawable.sugar_syrup
        49 -> R.drawable.milk
        50 -> R.drawable.strawberries
        51 -> R.drawable.chocolate_syrup
        52 -> R.drawable.yoghurt
        53 -> R.drawable.mango
        54 -> R.drawable.ginger
        55 -> R.drawable.lime
        56 -> R.drawable.cantaloupe
        57 -> R.drawable.berries
        58 -> R.drawable.grapes
        59 -> R.drawable.kiwi
        60 -> R.drawable.tomato_juice
        61 -> R.drawable.cocoa_powder
        62 -> R.drawable.chocolate
        63 -> R.drawable.heavy_cream
        64 -> R.drawable.galliano
        65 -> R.drawable.peach_vodka
        66 -> R.drawable.ouzo
        67 -> R.drawable.coffee
        68 -> R.drawable.spiced_rum
        69 -> R.drawable.water
        70 -> R.drawable.espresso
        71 -> R.drawable.angelica_root
        72 -> R.drawable.orange
        73 -> R.drawable.cranberries
        74 -> R.drawable.johnie_walker
        75 -> R.drawable.apple_cider
        76 -> R.drawable.everclear
        77 -> R.drawable.cranberry_juice
        78 -> R.drawable.egg_yolk
        79 -> R.drawable.egg
        80 -> R.drawable.grape_juice
        81 -> R.drawable.peach_nectar
        82 -> R.drawable.lemon
        83 -> R.drawable.firewater
        84 -> R.drawable.lemonade
        85 -> R.drawable.lager
        86 -> R.drawable.whiskey
        87 -> R.drawable.absolut_citron
        88 -> R.drawable.pisco
        89 -> R.drawable.irish_cream
        90 -> R.drawable.ale
        91 -> R.drawable.chocolate_liqueur
        92 -> R.drawable.midori_melon
        93 -> R.drawable.sambuka
        94 -> R.drawable.cider
        95 -> R.drawable.sprite
        96 -> R.drawable.seven_up
        97 -> R.drawable.blackberry_brandy
        98 -> R.drawable.peppermint_schnapps
        99 -> R.drawable.creme_de_cassis
        // Add more cases for other items as needed.
        else -> R.drawable.vodka
    }
}