package com.example.ui.ingredients

import com.example.ui.R

fun getStringResourceId(index: Int): Int {
    return when (index) {
        0 -> R.string.light_rum_description
        1 -> R.string.applejack_description
        2 -> R.string.gin_description
        3 -> R.string.dark_rum_description
        4 -> R.string.sweet_vermout_description
        5 -> R.string.strawberry_schnapps_description
        6 -> R.string.scotch_description
        7 -> R.string.apricot_brandy_description
        8 -> R.string.triple_sec_description
        9 -> R.string.southern_comfort_description
        10 -> R.string.orange_bitters_description
        11 -> R.string.brandy_description
        12 -> R.string.lemon_vodka_description
        13 -> R.string.blended_whiskey_description
        14 -> R.string.dry_vermouth_description
        15 -> R.string.amaretto_description
        16 -> R.string.tea_description
        17 -> R.string.champagne_description
        18 -> R.string.coffee_liqueur_description
        19 -> R.string.bourbon_description
        20 -> R.string.tequila_description
        21 -> R.string.vodka_description
        22 -> R.string.aneyo_rum_description
        23 -> R.string.bitters_description
        24 -> R.string.sugar_description
        25 -> R.string.kahlua_description
        26 -> R.string.demerara_sugar_description
        27 -> R.string.dubonnet_rouge_description
        28 -> R.string.watermelon_description
        29 -> R.string.lime_juice_description
        30 -> R.string.irish_whiskey_description
        31 -> R.string.apple_brandy_description
        32 -> R.string.carbonated_water_description
        33 -> R.string.cherry_brandy_description
        34 -> R.string.creme_de_cacao_description
        35 -> R.string.grenadine_description
        36 -> R.string.port_description
        37 -> R.string.coffee_brandy_description
        38 -> R.string.red_wine_description
        39 -> R.string.rum_description
        40 -> R.string.grapefruit_juice_description
        41 -> R.string.ricard_description
        42 -> R.string.sherry_description
        43 -> R.string.cognac_description
        44 -> R.string.sloe_gin_description
        45 -> R.string.apple_juice_description
        46 -> R.string.pineapple_juice_description
        47 -> R.string.lemon_juice_description
        48 -> R.string.sugar_syrup_description
        49 -> R.string.milk_description
        50 -> R.string.strawberries_description
        51 -> R.string.chocolate_syrup_description
        52 -> R.string.yoghurt_description
        53 -> R.string.mango_description
        54 -> R.string.ginger_description
        55 -> R.string.lime_description
        56 -> R.string.cantaloupe_description
        57 -> R.string.berries_description
        58 -> R.string.grapes_description
        59 -> R.string.kiwi_description
        60 -> R.string.tomato_juice_description
        61 -> R.string.cocoa_powder_description
        62 -> R.string.chocolate_description
        63 -> R.string.heavy_cream_description
        64 -> R.string.galliano_description
        65 -> R.string.peach_vodka_description
        66 -> R.string.ouzo_description
        67 -> R.string.coffee_description
        68 -> R.string.spiced_rum_description
        69 -> R.string.water_description
        70 -> R.string.espresso_description
        71 -> R.string.angelica_root_description
        72 -> R.string.orange_description
        73 -> R.string.cranberries_description
        74 -> R.string.johnie_walker_description
        75 -> R.string.apple_cider_description
        76 -> R.string.everclear_description
        77 -> R.string.cranberry_juice_description
        78 -> R.string.egg_yolk_description
        79 -> R.string.egg_description
        80 -> R.string.grape_juice_description
        81 -> R.string.peach_nectar_description
        82 -> R.string.lemon_description
        83 -> R.string.firewater_description
        84 -> R.string.lemonade_description
        85 -> R.string.lager_description
        86 -> R.string.whiskey_description
        87 -> R.string.absolut_citron_description
        88 -> R.string.pisco_description
        89 -> R.string.irish_cream_description
        90 -> R.string.ale_description
        91 -> R.string.chocolate_liquer_description
        92 -> R.string.midori_melon_liqueur_description
        93 -> R.string.sambuca_description
        94 -> R.string.cider_description
        95 -> R.string.sprite_description
        96 -> R.string.seven_up_description
        97 -> R.string.blackberry_brandy_description
        98 -> R.string.peppermint_schnapps_description
        99 -> R.string.creme_de_cassis_description
        // Add more cases for other items as needed.
        else -> R.string.creme_de_cassis_description
    }
}